services:
  birthday-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: birthday-etin-app
    restart: always
    volumes:
      - ./dist:/app/dist
      - ./public:/app/public
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.etinbirthday.entrypoints=web"
      - "traefik.http.routers.etinbirthday.rule=Host(`etinbirthday.dthrees.my.id`)"
      - "traefik.http.services.etinbirthday.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true

